import {
    Activity,
    ArrowDownUp,
    BellRing,
    BookOpen,
    Briefcase,
    CircleUserRound,
    Cog,
    GraduationCap,
    Landmark,
    LayoutDashboard,
    LineChart,
    PiggyBank,
    Shield,
    TrendingUp,
    Users,
    Wallet,
    Waypoints,
} from 'lucide-react';

export const dashboardSections = [
    {
        id: 'overview',
        label: 'Dashboard',
        helper: 'See all your tools at a glance',
        icon: LayoutDashboard,
        accent: 'from-slate-800 via-slate-900 to-primary-900',
        iconBg: 'bg-slate-900 text-white',
        badge: 'Home',
        description: 'Your welcome hub for navigating every Shilingi Moves dashboard tool.',
        group: 'main',
        topTab: true,
    },
    {
        id: 'cashflow',
        label: 'Income Manager',
        helper: 'Track money coming in',
        icon: ArrowDownUp,
        accent: 'from-primary-500 to-emerald-600',
        iconBg: 'bg-primary-100 text-primary-700',
        badge: 'Core',
        description: 'Track salary, business income, and other money coming in.',
        group: 'planning',
    },
    {
        id: 'budget',
        label: 'Budget Planner',
        helper: 'Plan spending and save smart',
        icon: Wallet,
        accent: 'from-amber-300 to-amber-500',
        iconBg: 'bg-amber-100 text-amber-700',
        badge: 'Plan',
        description: 'Track income and expenses to understand where your money goes.',
        group: 'planning',
    },
    {
        id: 'debt',
        label: 'Debt Manager',
        helper: 'Track and reduce what you owe',
        icon: Landmark,
        accent: 'from-rose-400 to-red-500',
        iconBg: 'bg-rose-100 text-rose-700',
        badge: 'Reduce',
        description: 'Track what you owe, plan your repayments, and reduce debt.',
        group: 'planning',
    },
    {
        id: 'investments',
        label: 'Investment Planner',
        helper: 'Track and grow investments',
        icon: LineChart,
        accent: 'from-sky-500 to-blue-600',
        iconBg: 'bg-sky-100 text-sky-700',
        badge: 'Grow',
        description: 'Plan and track your investments while monitoring growth.',
        group: 'planning',
    },
    {
        id: 'protection',
        label: 'Protection Planner',
        helper: 'Safeguard what matters',
        icon: Shield,
        accent: 'from-emerald-400 to-teal-500',
        iconBg: 'bg-emerald-100 text-emerald-700',
        badge: 'Protect',
        description: 'Review cover gaps, compare products, and estimate protection needs.',
        group: 'planning',
    },
    {
        id: 'retirement',
        label: 'Retirement Planner',
        helper: 'Prepare for future income',
        icon: PiggyBank,
        accent: 'from-violet-400 to-fuchsia-500',
        iconBg: 'bg-violet-100 text-violet-700',
        badge: 'Future',
        description: 'Project retirement needs, compare products, and build a long-term plan.',
        group: 'planning',
    },
    {
        id: 'networth',
        label: 'Net Worth Planner',
        helper: 'Track assets and liabilities',
        icon: TrendingUp,
        accent: 'from-violet-500 to-indigo-600',
        iconBg: 'bg-violet-100 text-violet-700',
        badge: 'View',
        description: 'Calculate your total net worth from assets and liabilities.',
        group: 'planning',
    },
    {
        id: 'comparehub',
        label: 'Compare Hub',
        topLabel: 'Compare',
        helper: 'Compare products side by side',
        icon: Waypoints,
        accent: 'from-sky-500 to-cyan-600',
        iconBg: 'bg-sky-100 text-sky-700',
        badge: 'Explore',
        description: 'Review loans, savings, investments, insurance, and more in one place.',
        group: 'explore',
        topTab: true,
    },
    {
        id: 'resourceshub',
        label: 'Resources & Tools',
        topLabel: 'Resources',
        helper: 'Use calculators and curated content',
        icon: Briefcase,
        accent: 'from-amber-300 to-orange-500',
        iconBg: 'bg-amber-100 text-amber-700',
        badge: 'Resources',
        description: 'Open financial calculators, curated books, podcasts, and tools.',
        group: 'explore',
        topTab: true,
    },
    {
        id: 'learninghub',
        label: 'Learning Hub',
        topLabel: 'Learning Hub',
        helper: 'Grow your money knowledge',
        icon: GraduationCap,
        accent: 'from-emerald-400 to-teal-600',
        iconBg: 'bg-emerald-100 text-emerald-700',
        badge: 'Learn',
        description: 'Follow learning paths, expert articles, videos, games, and quizzes.',
        group: 'explore',
        topTab: true,
    },
    {
        id: 'communityhub',
        label: 'Community',
        topLabel: 'Community',
        helper: 'Learn with others and stay accountable',
        icon: Users,
        accent: 'from-primary-500 to-emerald-600',
        iconBg: 'bg-primary-100 text-primary-700',
        badge: 'Community',
        description: 'Join events, discussions, and member challenges across the ecosystem.',
        group: 'explore',
        topTab: true,
    },
    {
        id: 'buddy',
        label: 'Shilingi Buddy AI',
        helper: 'Ask for guidance anytime',
        icon: BellRing,
        accent: 'from-slate-700 to-slate-900',
        iconBg: 'bg-slate-100 text-slate-700',
        badge: 'Assist',
        description: 'Get nudges, weekly prompts, and personalized next steps for your money goals.',
        group: 'insights',
    },
    {
        id: 'marketwatch',
        label: 'Market Watch',
        helper: 'See signals that affect your plans',
        icon: LineChart,
        accent: 'from-sky-500 to-blue-700',
        iconBg: 'bg-sky-100 text-sky-700',
        badge: 'Watch',
        description: 'Track rates, product movements, and market themes relevant to your plans.',
        group: 'insights',
    },
    {
        id: 'health',
        label: 'Financial Health Overview',
        helper: 'Monitor your financial readiness',
        icon: Activity,
        accent: 'from-teal-500 to-emerald-600',
        iconBg: 'bg-teal-100 text-teal-700',
        badge: 'Score',
        description: 'Check your financial wellness score and spot areas to improve.',
        group: 'insights',
    },
    {
        id: 'user',
        label: 'Profile',
        helper: 'Manage your money profile',
        icon: CircleUserRound,
        accent: 'from-slate-600 to-slate-800',
        iconBg: 'bg-slate-100 text-slate-700',
        badge: 'Profile',
        description: 'Update your account details, preferences, and personal information.',
        group: 'main',
    },
    {
        id: 'settings',
        label: 'Settings',
        helper: 'Manage security and preferences',
        icon: Cog,
        accent: 'from-emerald-500 to-teal-600',
        iconBg: 'bg-emerald-100 text-emerald-700',
        badge: 'Settings',
        description: 'Update notification, security, and display preferences.',
    },
    {
        id: 'advisory',
        label: 'Shilingi Guidance',
        helper: 'Kenyan money tools built around you',
        icon: Briefcase,
        accent: 'from-primary-600 to-amber-400',
        iconBg: 'bg-primary-100 text-primary-700',
        badge: 'Why it matters',
        description: 'A practical dashboard shaped for savings, debt reduction, growth, and clarity.',
    },
];

export const dashboardSidebarGroups = [
    {
        id: 'main',
        label: 'Main',
        items: ['overview', 'user'],
    },
    {
        id: 'planning',
        label: 'Planning tools',
        items: ['budget', 'debt', 'investments', 'protection', 'retirement', 'networth'],
    },
    {
        id: 'explore',
        label: 'Explore',
        items: ['comparehub', 'resourceshub', 'learninghub', 'communityhub'],
    },
    {
        id: 'insights',
        label: 'Insights',
        items: ['buddy', 'marketwatch', 'health'],
    },
];

export const dashboardTopTabs = ['overview', 'comparehub', 'resourceshub', 'learninghub', 'communityhub']
    .map((id) => dashboardSections.find((section) => section.id === id))
    .filter(Boolean);

export const dashboardNavSections = dashboardSections.filter((section) =>
    [
        'overview',
        'budget',
        'cashflow',
        'debt',
        'investments',
        'protection',
        'retirement',
        'networth',
        'comparehub',
        'resourceshub',
        'learninghub',
        'communityhub',
        'buddy',
        'marketwatch',
        'health',
        'user',
        'settings',
    ].includes(section.id)
);

export const dashboardSectionMap = dashboardSections.reduce((accumulator, section) => {
    accumulator[section.id] = section;
    return accumulator;
}, {});
